language: c
git:
  submodules: false

env: B=autotools

install:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      autoconf-archive
      bison
      docbook-xsl
      flex
      gradle-2.2.1
      libcap-dev
      libdbd-sqlite3
      libdbi0-dev
      libesmtp-dev
      libevtlog-dev
      libgeoip-dev
      libglib2.0-dev
      libhiredis-dev
      libivykis-dev
      libjson0-dev
      libnet1-dev
      libriemann-client-dev
      libwrap0-dev
      pkg-config
      sqlite3
      xsltproc
  - sudo pip install -r requirements.txt
before_script:
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - CONFIGURE_FLAGS="
      CFLAGS=-Werror
      --prefix=$HOME/install/syslog-ng
      --with-ivykis=internal
      --with-mongoc=internal
      --with-librabbitmq=internal
      --with-jsonc=system
      --disable-env-wrapper
      --disable-memtrace
      --enable-tcp-wrapper
      --enable-linux-caps
      --disable-sun-streams
      --enable-all-modules
      --disable-sql
      --enable-pacct
      --enable-manpages
      --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
      --enable-extra-warnings
      "
  - ./configure $CONFIGURE_FLAGS
script:
  - . tests/build-log-cflags-propagation.sh;
    if [ "$CC" = "gcc" ]; then
      export DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_FLAGS";
      exec_prop_check "make distcheck V=1 --keep-going" ||
      {
        S=$?;
        make V=1 distcheck;
        find . -name test-suite.log |
        xargs cat;
        return $S;
      };
    else
      make --keep-going -j install;
      S=$?;
      if [ "$S" = "0" ]; then
        . scripts/get-libjvm-path.sh || return $?;
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$JNI_LIBDIR";
        make func-test V=1;
      elif [ "$S" = "42" ]; then
        return $S;
      else
        make V=1 install;
        return $S;
      fi;
    fi
compiler:
  - gcc
  - clang

matrix:
  include:
    - env: B=copyright-check
      sudo: false
      compiler: gcc
      install:
      before_script:
      script:
        - export COPYRIGHTVERBOSITY=1
        - tests/copyright/check.sh . .
    - env: B=trusty-cmake
      compiler: clang
      dist: trusty
      sudo: required
      before_script:
      script:
        - mkdir build
        - cd build
        - cmake
            -DCMAKE_C_FLAGS=-Werror
            -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
            ..
        - make --keep-going -j install ||
          {
            S=$?;
            make V=1 install;
            return $S;
          }

branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
