language: c

matrix:
  include:
    compiler:
      - gcc
#      - clang
  include:
    - env: E=copyright_check
      sudo: false
    - script:
      - export COPYRIGHTVERBOSITY=1;
        tests/copyright/check.sh . .
    - env: E=precise_container
      sudo: false
      cache:
        directories:
          - $HOME/.local/bin
          - $HOME/.local/gradle-2.9
          - $HOME/.local/include
          - $HOME/.local/lib
          - $HOME/.local/man
          - $HOME/.cache/pip
          - $HOME/.ccache
          - $HOME/.gradle/caches
          - .autoconf
          - autom4te.cache
      before_cache:
        - rm -f $HOME/.cache/pip/log/debug.log
        - du -s $HOME/.cache/* $HOME/.ccache/* .autoconf autom4te.cache
        - ccache -s
        - ls -la $HOME $HOME/.[^.]* $HOME/..?*
      addons:
        apt:
          packages:
            - ccache
            - pkg-config
            - flex
            - bison
            - xsltproc
            - docbook-xsl
            - libevtlog-dev
            - libevtlog0
            - libnet1-dev
            - libglib2.0-dev
            - libhiredis-dev
#            - libdbi-dev # old libdbi0-dev ?
            - libssl-dev
            - libjson0-dev
            - libwrap0-dev
            - libpcre3-dev
            - libcap-dev
            - libesmtp-dev
            - libesmtp6
            - libssl1.0.0
            - libgeoip-dev
            - sqlite3
            - libdbd-sqlite3
      #      - libriemann-client-dev # disallowed
      #      - libriemann-client0 # dep disallowed
            - libprotobuf-c0-dev
            - openjdk-7-jdk
      #      - gradle # the one in 12.04 is buggy, one in 14.04 seems fine
            - autoconf-archive
      install:
        - export PATH=/usr/lib/ccache:$PATH
        - export PATH=$HOME/.local/bin:$PATH
        - ccache -z
      #  - if [ "$CC" = "clang" ]; then export CCACHE_CPP2=yes; fi
        - echo "max_size = 150M" > ~/.ccache/ccache.conf
        - if [ "$CC" = "clang" ]; then printf "run_second_cpp = true\nprefix_command = -Qunused-arguments\n" >> ~/.ccache/ccache.conf; fi
        - rm $HOME/.local/bin/clang; true; # if ! [ -f $HOME/.local/bin/clang ]; then ln -s `which ccache` $HOME/.local/bin/clang; fi
      #  - printf '#!/bin/sh\nCCACHE_CPP2=yes exec ccache clang "$@"\n' > $HOME/.local/bin/clang; chmod +x $HOME/.local/bin/clang
      #  - echo 'CCACHE_CPP2=yes exec ccache clang -Qunused-arguments `test -t 2 && echo -fcolor-diagnostics` "$@"' > $HOME/.local/bin/clang; chmod +x $HOME/.local/bin/clang
        - pip install --user -r requirements.txt
        - export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH; if ! pkg-config --exists eventlog; then apt-get source eventlog && cd eventlog-* && { ./autogen.sh && ./configure --prefix=$HOME/.local/ && make -j install && cd .. && rm -R eventlog* ; }; fi
        - export GRADLE_HOME=$HOME/.local/gradle-2.9 && export PATH=$GRADLE_HOME/bin:$PATH; if ! which gradle; then wget https://downloads.gradle.org/distributions/gradle-2.9-bin.zip && { unzip gradle-2.9-bin.zip -d $HOME/.local/ && rm -v gradle-2.9-bin.zip; }; fi
      before_script:
        - ./autogen.sh
        - env
        - unset PYTHON_CFLAGS # HACK
        - ./configure
            CFLAGS=-Werror
            --with-ivykis=internal
            --with-mongoc=internal
            --with-librabbitmq=internal
            --with-jsonc=system
            --prefix=$HOME/install/syslog-ng
            --disable-env-wrapper
            --disable-memtrace
            --enable-tcp-wrapper
            --disable-sun-streams
            --enable-linux-caps
            --disable-systemd
            --with-systemd-journal=optional
            --enable-manpages
            --disable-sql
            --disable-redis
            --disable-riemann
            --enable-all-modules
            --with-docbook-dir=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
      after_script:
        - ccache -s
    - env: E=trusty
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - curl
            - wget
            - ccache
            - pkg-config
            - flex
            - bison
            - xsltproc
            - docbook-xsl
            - libevtlog-dev
            - libevtlog0
            - libnet1-dev
            - libglib2.0-dev
            - libhiredis-dev
            - libdbi0-dev
            - libssl-dev
#            - libjson0-dev
            - libwrap0-dev
            - libpcre3-dev
            - libcap-dev
            - libesmtp-dev
            - libesmtp6
            - libssl1.0.0
            - libgeoip-dev
            - sqlite3
            - libdbd-sqlite3
            - libriemann-client-dev # disallowed
            - libriemann-client0 # dep disallowed
            - libprotobuf-c0-dev
            - openjdk-7-jdk
            - gradle
            - autoconf-archive
      install:
        - cat /etc/apt/sources.list
        - sudo sed -ri "s~^(deb(-src)?) http://us\.archive\.ubuntu\.com/ubuntu/( .*)$~\1 mirror://mirrors.ubuntu.com/mirrors.txt\3~" /etc/apt/sources.list
        - cat /etc/apt/sources.list
#        - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
#        - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" |
#          sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
#        - sudo apt-get update -qq
#        - sudo apt-get install -qq gradle-2.2.1
        - sudo pip install -r requirements.txt
      before_script:
        - ./autogen.sh
        - unset PYTHON_CFLAGS # HACK
        - ./configure
            CFLAGS=-Werror
            --with-ivykis=internal
            --with-mongoc=internal
            --with-librabbitmq=internal
            --with-jsonc=internal
            --prefix=$HOME/install/syslog-ng
            --disable-env-wrapper
            --disable-memtrace
            --enable-tcp-wrapper
            --disable-sun-streams
            --enable-linux-caps
            --disable-systemd
            --with-systemd-journal=system
            --enable-manpages
            --enable-all-modules
            --with-docbook-dir=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
script:
  - make -j ||
      make V=1 --keep-going # to make error messages more readable on error
  - if [ "$CC" = "gcc" ]; then
      make distcheck V=1;
    else
      make install &&
        make func-test V=1;
    fi
branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
