language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq curl
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config flex bison xsltproc docbook-xsl libevtlog-dev libnet1-dev libglib2.0-dev libdbi0-dev libssl-dev libjson0-dev libwrap0-dev libpcre3-dev libcap-dev libesmtp-dev libgeoip-dev libhiredis-dev sqlite3 libdbd-sqlite3 libriemann-client-dev openjdk-7-jdk gradle-2.2.1 autoconf-archive # libsystemd-journal-dev libsystemd-daemon-dev
  - sudo pip install -r requirements.txt
before_script:
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - ./configure
      CFLAGS=-Werror
      --with-ivykis=internal
      --with-mongoc=internal
      --with-librabbitmq=internal
      --with-jsonc=internal
      --prefix=$HOME/install/syslog-ng
      --disable-env-wrapper
      --disable-memtrace
      --enable-ipv6
      --enable-tcp-wrapper
      --enable-spoof-source
      --disable-sun-streams
      --enable-sql
      --enable-pacct
      --enable-linux-caps
      --enable-mongodb
      --enable-json
      --enable-amqp
      --enable-stomp
      --enable-smtp
      --enable-redis
      --disable-systemd
      --enable-geoip
      --enable-riemann
      --enable-systemd-journal=optional
      --enable-python
      --enable-manpages
      --enable-java
      --enable-java-modules
      --enable-native
      --enable-all-modules
      --with-docbook-dir=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
  - if [ "$CC" = "clang" ]; then export COPYRIGHTVERBOSITY=1; make check-copyright; fi
  - make -j || make V=1 --keep-going # to make error messages more readable on error
script:
  - if [ "$CC" = "gcc" ]; then make distcheck V=1; else make install && make func-test V=1; fi
compiler:
  - gcc
  - clang
branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
