language: c
git:
  submodules: false

env: B=autotools

install:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config flex bison xsltproc docbook-xsl libivykis-dev libevtlog-dev libnet1-dev libglib2.0-dev libdbi0-dev libjson0-dev libwrap0-dev libcap-dev libesmtp-dev libgeoip-dev libhiredis-dev sqlite3 libdbd-sqlite3 libriemann-client-dev gradle-2.2.1 autoconf-archive
  - sudo pip install -r requirements.txt
before_script:
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - ./configure CFLAGS=-Werror --with-ivykis=internal --prefix=$HOME/install/syslog-ng --enable-pacct --enable-manpages --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl 
  - make -j || make V=1 --keep-going # to make error messages more readable on error
script:
  - if [ "$CC" = "gcc" ]; then make distcheck V=1; else make func-test V=1; fi
compiler:
  - gcc
  - clang

matrix:
  include:
    - env: B=copyright-check
      sudo: false
      compiler: gcc
      install:
      before_script:
      script:
        - export COPYRIGHTVERBOSITY=2
        - tests/copyright/check.sh . .
    - env: B=trusty-cmake
      compiler: clang
      dist: trusty
      sudo: required
      before_script:
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_C_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng ..
        - make -j install

branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
