language: c
git:
  submodules: false

env: B=autotools

install:
  - travis_retry curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq pkg-config flex bison xsltproc docbook-xsl libivykis-dev libevtlog-dev libnet1-dev libglib2.0-dev libdbi0-dev libjson0-dev libwrap0-dev libcap-dev libesmtp-dev libgeoip-dev libhiredis-dev sqlite3 libdbd-sqlite3 libriemann-client-dev gradle-2.2.1 autoconf-archive ninja-build
  - travis_retry sudo pip install -r requirements.txt
before_script:
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - ./configure CFLAGS=-Werror --with-ivykis=internal --prefix=$HOME/install/syslog-ng --enable-pacct --enable-manpages --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl --enable-extra-warnings
  - . tests/build-log-cflags-propagation.sh;
    exec_prop_check "make -j V=1 --keep-going";
    S=$?;
    if [ "$S" = "42" -o "$S" = "0" ]; then
      return $S;
    else
      make V=1; false;
    fi # to make error messages more readable on error
script:
  - if [ "$CC" = "gcc" ]; then
      . tests/build-log-cflags-propagation.sh;
      export DISTCHECK_CONFIGURE_FLAGS="CFLAGS=-Werror --enable-extra-warnings";
      exec_prop_check "make distcheck V=1 --keep-going";
    else
      make func-test V=1;
    fi
compiler:
  - gcc
  - clang

matrix:
  include:
    - env: B=copyright-check
      sudo: false
      compiler: gcc
      install:
      before_script:
      script:
        - export COPYRIGHTVERBOSITY=2
        - tests/copyright/check.sh . .
    - env: B=trusty-cmake
      compiler: clang
      dist: trusty
      sudo: required
      before_script:
      script:
        - mkdir build
        - cd build
        - cmake -GNinja -DCMAKE_C_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng ..
        - ninja install

branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
