language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq curl
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config flex bison xsltproc docbook-xsl libevtlog-dev libnet1-dev libglib2.0-dev libdbi0-dev libssl-dev libjson0-dev libwrap0-dev libpcre3-dev libcap-dev libesmtp-dev libgeoip-dev libhiredis-dev sqlite3 libdbd-sqlite3 libriemann-client-dev openjdk-7-jdk gradle-2.2.1 autoconf-archive
  - sudo pip install -r requirements.txt
before_script:
  - ./autogen.sh
  - unset PYTHON_CFLAGS # HACK
  - ./configure CFLAGS=-Werror --with-ivykis=internal --prefix=$HOME/install/syslog-ng --enable-pacct --enable-manpages --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl --enable-extra-warnings
  - if [ "$CC" = "clang" ]; then export COPYRIGHTVERBOSITY=1; make check-copyright; fi
  - . tests/build-log-cflags-propagation.sh;
    exec_prop_check "make -j V=1";
    S=$?;
    if [ "$S" = "42" -o "$S" = "0" ]; then
      return $S;
    else
      make V=1 --keep-going; false;
    fi # to make error messages more readable on error
script:
  - if [ "$CC" = "gcc" ]; then
      . tests/build-log-cflags-propagation.sh;
      export DISTCHECK_CONFIGURE_FLAGS="CFLAGS=-Werror --enable-extra-warnings";
      exec_prop_check "make distcheck V=1 --keep-going";
    else
      make func-test V=1;
    fi
compiler:
  - gcc
  - clang
branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/1c6e3a6f10348748585a
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false
